# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

PET <- function(model, hemis, inputData, elev, param) {
    .Call(`_HBV_IANIGLA_PET`, model, hemis, inputData, elev, param)
}

Glacier_Disch <- function(model, inputData, initCond, param) {
    .Call(`_HBV_IANIGLA_Glacier_Disch`, model, inputData, initCond, param)
}

Precip_model <- function(model, inputData, zmeteo, ztopo, param) {
    .Call(`_HBV_IANIGLA_Precip_model`, model, inputData, zmeteo, ztopo, param)
}

Routing_HBV <- function(model, lake, inputData, initCond, param) {
    .Call(`_HBV_IANIGLA_Routing_HBV`, model, lake, inputData, initCond, param)
}

SnowGlacier_HBV <- function(model, inputData, initCond, param) {
    .Call(`_HBV_IANIGLA_SnowGlacier_HBV`, model, inputData, initCond, param)
}

Soil_HBV <- function(model, inputData, initCond, param) {
    .Call(`_HBV_IANIGLA_Soil_HBV`, model, inputData, initCond, param)
}

Temp_model <- function(model, inputData, zmeteo, ztopo, param) {
    .Call(`_HBV_IANIGLA_Temp_model`, model, inputData, zmeteo, ztopo, param)
}

UH <- function(model, Qg, param) {
    .Call(`_HBV_IANIGLA_UH`, model, Qg, param)
}

medianCpp <- function(x) {
    .Call(`_HBV_IANIGLA_medianCpp`, x)
}

